filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'

checks:
  php: true

coding_style:
  php: {  }


build:
  nodes:
    my-tests-with-coverage:
      environment:
        php: 7.4
      dependencies:
        override:
          - composer install --no-interaction --prefer-source --dev
      tests:
        override:
          - command: phpunit --coverage-clover=my-coverage-file
            coverage:
              file: my-coverage-file
              format: php-clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
