filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'

checks:
  php: true

coding_style:
  php: {  }

build:
  environment:
    php: 7.4
  dependencies:
    override:
      - composer install --no-interaction --prefer-source --dev
  tests:
    override:
      -
        command: bin/phpunit --coverage-clover=clover.xml
        coverage:
          file: clover.xml
          format: php-clover
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
