coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/**/*"
  - "vendor/**/*"

codecov:
  branch: main # set new Default branch